# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Checks on merging to master

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * *' # runs at midnight, to update cache

env:
  CACHE_NUMBER: 1  # increase to reset cache manually

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9.x
      uses: actions/setup-python@v5
      with:
        python-version: "3.9.12"
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3.0.1
      with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: data-science
          use-mamba: true
    - name: Set cache date
      run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
    - uses: actions/cache@v4
      with:
        path: /usr/share/miniconda3 # this is where the base conda environment lives
        key: conda-${{ hashFiles('environment.yml') }}-${{ hashFiles('environment-dev.yml') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
      id: cache
    - name: Update environment
      run: |
        mamba env update -n data-science -f environment.yml
        mamba env update -n data-science -f environment-dev.yml
        mamba env update -n data-science -f environment-exploration.yml
      if: steps.cache.outputs.cache-hit != 'true'
    - name: pre-commit all things
      shell: bash -l {0}
      run: |
        pre-commit run --all-files
